# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://lobocv.com/"
DefaultContentLanguage  = "en"
title                   = "Lobocv Blog"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
unsafe                = true

[outputs]
home                  = ["html", "json", "rss"]

[params]
enableCDN             = false
cssFiles              = ["default"]
jsFiles               = ["default"]
highlightjs           = true
highlightjsTheme      = ""
highlightjsLang       = []
viewMorePostsLink     = "/blog/"
readingTime           = true
imageStretch          = ""
removeBlur            = false
socialShare           = ["twitter", "facebook", "reddit", "linkedin", "email"]
hideEmptyStats        = false

[params.meta]
description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
author              = "Calvin V Lobo"
favicon             = false
svg                 = true
faviconVersion      = "1"
msColor             = "#ffffff"
iOSColor            = "#ffffff"

[params.header]
navbarTitle         = "lobocv"
dynamicTitles       = true
searchMenu          = true
shareMenu           = true
languageMenu        = true

[params.intro]
header                = "blog"
paragraph             = "Software design, architecture and philosophy"
rssIntro              = true
socialIntro           = true
hideWhenSingleColumn  = false
alwaysOnHomepage      = false

[params.intro.pic]
src                 = "img/logo.jpg"
shape               = "circle"
width               = "250px"
alt                 = ""

[params.sidebar]
about               = "Software and tech enthusiast"
postAmount          = 5
categories          = true
categoriesByCount   = true

[params.footer]
rssFooter           = true
socialFooter        = true

[params.utterances]
enabled             = false
repo                = ""
issueTerm           = "pathname"
issueNumber         = ""
label               = ""
theme               = "github-light"

[params.staticman]
enabled             = true
api                 = ""  # No Trailing Slash
gitProvider         = ""
username            = ""
repo                = ""
branch              = ""

[params.staticman.recaptcha]
siteKey           = ""
encryptedKey      = ""

[menu]

[[menu.main]]
name              = "Home"
identifier        = "home"
url               = "/"
pre               = "<i class='fa fa-home'></i>"
weight            = 1

[[menu.main]]
name              = "About"
identifier        = "about"
url               = "/about/"
pre               = "<i class='far fa-id-card'></i>"
weight            = 2

#[[menu.main]]
#name              = "Blog"
#identifier        = "blog"
#url               = "/blog/"
#pre               = "<i class='far fa-newspaper'></i>"
#weight            = 3

[[menu.main]]
name              = "Categories"
identifier        = "categories"
url               = "/categories/"
pre               = "<i class='fas fa-sitemap'></i>"
weight            = 5

[[menu.main]]
name              = "Contact"
identifier        = "contact"
url               = "/contact/"
pre               = "<i class='far fa-envelope'></i>"
weight            = 6


[Languages]
#
#[Languages.en]
#LanguageCode        = "en"
#LanguageName        = "English"
#weight              = 1

[social]
# Coding Communities
github                = "lobocv"
# Professional/Business Oriented Communities
linkedin              = "lobocv"
# Email
email                 = "calvinvlobo@gmail.com"
